apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: loadbalancer-serving-cert
  namespace: wz-system
spec:
  dnsNames:
    - loadbalancer-webhook-service.wz-system.svc
    - loadbalancer-webhook-service.wz-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: loadbalancer-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: loadbalancer-selfsigned-issuer
  namespace: wz-system
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: wz-system/loadbalancer-serving-cert
  name: loadbalancer-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: loadbalancer-webhook-service
        namespace: wz-system
        path: /validate-v1-pod
    failurePolicy: Ignore
    name: banpods.x.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - DELETE
        resources:
          - pods
    sideEffects: NoneOnDryRun
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: wz-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loadbalancer-leader-election-role
  namespace: wz-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: loadbalancer-manager-role
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - network.x.wz.net
    resources:
      - loadbalancers
      - loadbalancers/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loadbalancer-leader-election-rolebinding
  namespace: wz-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loadbalancer-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: wz-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loadbalancer-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loadbalancer-manager-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: wz-system
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-webhook-service
  namespace: wz-system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
---