---
- hosts: "{{ group }}"
# serial: 1
  tasks:
    - lineinfile: dest=/etc/sysctl.d/99-sysctl.conf state=absent
            regexp="^net\.ipv6"
    - sysctl:
        name: net.core.somaxconn
        value: 1000
        state: present
    - sysctl:
        name: net.core.netdev_max_backlog
        value: 5000
        state: present
    - sysctl:
        name: net.core.rmem_default
        value: 16777216
        state: present
    - sysctl:
        name: net.core.rmem_max
        value: 16777216
        state: present
    - sysctl:
        name: net.core.wmem_default
        value: 16777216
        state: present
    - sysctl:
        name: net.core.wmem_max
        value: 16777216
        state: present
    - sysctl:
        name: net.ipv4.tcp_wmem
        value: 4096 12582912 16777216
        state: present
    - sysctl:
        name: net.ipv4.tcp_rmem
        value: 4096 12582912 16777216
        state: present
    - sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: 8096
        state: present
    - sysctl:
        name: net.ipv4.tcp_slow_start_after_idle
        value: 0
        state: present
    - sysctl:
        name: net.ipv4.tcp_tw_reuse
        value: 1
        state: present
    - sysctl:
        name: net.ipv4.ip_local_port_range
        value: 10240 65535
        state: present
    - sysctl:
        name: net.unix.max_dgram_qlen
        value: 512
        state: present

    # conntrack related
    - sysctl:
        name: net.netfilter.nf_conntrack_tcp_timeout_established
        value: 86400
        state: present
    - sysctl:
        name: net.netfilter.nf_conntrack_tcp_timeout_time_wait
        value: 120
        state: present
    - sysctl:
        name: net.netfilter.nf_conntrack_tcp_timeout_close_wait
        value: 60
        state: present
    - sysctl:
        name: net.netfilter.nf_conntrack_tcp_timeout_fin_wait
        value: 120
        state: present
    - sysctl:
        name: net.netfilter.nf_conntrack_max
        value: "{{ (ansible_memtotal_mb * 1024 * 1024 / 16384)|int }}"
        state: present
  become: yes
  gather_facts: yes
