apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: cilium-bird
  name: cilium-bird
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: cilium-bird
  template:
    metadata:
      labels:
        k8s-app: cilium-bird
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - cilium-bird
            topologyKey: kubernetes.io/hostname
      containers:
      - image: harbor.wz.cn/rancher/cilium-bird:v1.0.4
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - pkill
              - "-9"
              - bird
        name: cilium-bird
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              /bin/bash <<'EOF'
              birdcl show protocols  | grep BGP | grep Established
              EOF
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
          requests:
            cpu: "1"
            memory: 1000Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/bird/
          name: bird-config
        - mountPath: /var/run/bird/
          name: bird-socket
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - env:
        - name: IDC
          value: idc2
        - name: GC_TIME
          value: "0"
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: harbor.wz.cn/rancher/cilium-bird-init:v1.0.7
        imagePullPolicy: IfNotPresent
        name: cilium-bird-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/bird/
          name: bird-config
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - emptyDir: {}
        name: bird-config
      - hostPath:
          path: /var/run/bird/
          type: ""
        name: bird-socket
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

