---
- hosts: "{{ group }}"
  tasks:
    - name: 安装系统工具
      yum: name=ack,htop,sysstat,mlocate,bash-completion,vim,deltarpm state=latest

    - name: 调整服务器配置
      command: tuned-adm profile throughput-performance

    - yum: name=ntp state=latest
    - service: name=ntpd enabled=yes
    - service: name=ntpd state=started

    - yum: name=numad state=latest
    - service: name=numad enabled=yes
    - service: name=numad state=started

#   - lineinfile: dest=/etc/sysctl.d/99-sysctl.conf state=present
#           line="net.bridge.bridge-nf-call-arptables = 1"
#   - lineinfile: dest=/etc/sysctl.d/99-sysctl.conf state=present
#           line="net.bridge.bridge-nf-call-ip6tables = 1"
#   - lineinfile: dest=/etc/sysctl.d/99-sysctl.conf state=present
#           line="net.bridge.bridge-nf-call-iptables = 1"
  become: yes
  gather_facts: no
