---
- hosts: "{{ group }}"
  tasks:
    - copy: src=../files/Docker.repo dest=/etc/yum.repos.d/
    - yum: name=docker-engine state=latest

    - copy: src=../files/system/docker.service.d dest=/etc/systemd/system/
    - lineinfile: dest=/etc/sysctl.d/99-sysctl.conf state=present
            line="net.bridge.bridge-nf-call-arptables = 1"
    - lineinfile: dest=/etc/sysctl.d/99-sysctl.conf state=present
            line="net.bridge.bridge-nf-call-ip6tables = 1"
    - lineinfile: dest=/etc/sysctl.d/99-sysctl.conf state=present
            line="net.bridge.bridge-nf-call-iptables = 1"

    - service: name=docker enabled=yes
    - service: name=docker state=started
  become: yes
  gather_facts: no
