apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: 2.1.1
  name: dcgm-exporter
  namespace: gpu-operator-resources
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: dcgm-exporter
      app.kubernetes.io/version: 2.1.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dcgm-exporter
        app.kubernetes.io/version: 2.1.1
        wz-pmonitor-group: dcgm-exporter
        wz-pmonitor-port: "9400"
        wz-pmonitor-type: exporter
      name: dcgm-exporter
    spec:
      initContainers:
        - name: waiting-for-nvidia-driver-daemonset
          image: harbor.wz.net/x./busybox:latest
          command: ["sleep", "10"]
      containers:
        - env:
            - name: DCGM_EXPORTER_LISTEN
              value: :9400
            - name: DCGM_EXPORTER_KUBERNETES
              value: "true"
          image: harbor.wz.cn/nvidia/dcgm-exporter:2.0.13-2.1.2-ubi8
          imagePullPolicy: IfNotPresent
          name: dcgm-exporter
          ports:
            - containerPort: 9400
              name: metrics
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
            runAsNonRoot: false
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/kubelet/pod-resources
              name: pod-gpu-resources
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /var/lib/kubelet/pod-resources
            type: ""
          name: pod-gpu-resources
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
