apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: gpu-operator-resources
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nvidia-device-plugin-daemonset
  template:
    metadata:
      labels:
        app: nvidia-device-plugin-daemonset
    spec:
      nodeSelector:
        wz.cloud/nvidia-gpu: "true"
      containers:
        - args:
            - --mig-strategy=single
            - --fail-on-init-error=true
            - --pass-device-specs
            - --device-list-strategy=envvar
            - --nvidia-driver-root=/run/nvidia/driver
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
          image: harbor.wz.cn/nvidia/k8s-device-plugin:v0.9.0-centos7
          imagePullPolicy: IfNotPresent
          name: nvidia-device-plugin-ctr
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/kubelet/device-plugins
              name: device-plugin
      dnsPolicy: ClusterFirst
      initContainers:
        - name: waiting-for-nvidia-driver-daemonset
          image: harbor.wz.net/x./busybox:latest
          command: ["sleep", "10"]
        - args:
            - /tmp/vectorAdd
          command:
            - sh
            - -c
          image: harbor.wz.cn/nvidia/cuda-sample:vectoradd-cuda10.2
          imagePullPolicy: IfNotPresent
          name: toolkit-validation
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /var/lib/kubelet/device-plugins
            type: ""
          name: device-plugin
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
