apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: device-plugin-evict-ds
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: gpushare-device-plugin
      app: gpushare
      name: device-plugin-evict-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        component: gpushare-device-plugin
        app: gpushare
        name: device-plugin-evict-ds
    spec:
      hostNetwork: true
      nodeSelector:
        wz.cloud/vgpu: "true"
      initContainers:
        - name: waiting-for-nvidia-driver-daemonset
          image: harbor.wz.net/x./busybox:latest
          command: ["sleep", "10"]
      containers:
      - name: gpushare
        {{- if .Values.pullImageByVPCNetwork }}
        image: "{{ .Values.images.evictor.image | replace "registry." "registry-vpc." }}:{{ .Values.images.evictor.tag }}"
        {{- else }}
        image: "{{ .Values.images.evictor.image }}:{{ .Values.images.evictor.tag }}"
        {{- end }}
        imagePullPolicy: {{ .Values.images.evictor.pullPolicy }}
        command: 
          - bash
          - /dp-evict/dp-evict-on-host.sh
        # Make this pod as Guaranteed pod which will never be evicted because of node's resource consumption.
        securityContext:
          privileged: true
        volumeMounts:
        - name: kube-dir
          mountPath: /etc/kubernetes
      volumes:
      - hostPath:
          path: /etc/kubernetes
          type: Directory
        name: kube-dir
