---

- hosts: "{{ group }}"
  tasks:
    - lvg:  vg=VolGroup01 pvs=/dev/md1
    # Docker library (/var/lib/docker/containers)
    - lvol: vg=VolGroup01 lv=LogVol00 size=300g
    - filesystem: fstype=xfs dev=/dev/VolGroup01/LogVol00
    - file: state=directory path=/var/lib/docker
    - mount: name=/var/lib/docker src=/dev/VolGroup01/LogVol00 fstype=xfs opts="defaults" state=mounted
    # Docker thin pool (/var/lib/docker/devicemapper)
    - command: lvcreate -L 500g --thin VolGroup01/ThinPool00

    # SWAP
    - command: swapoff -a
    - lineinfile:
        dest: /etc/fstab
        state: present
        regexp: '^(/dev/mapper/VolGroup00-LogVol00 swap.*)'
        line: '#\1'
        backrefs: yes

    # Path: /tmp
    - lvol: vg=VolGroup00 lv=LogVol01 size=4g
    - command: xfs_growfs /dev/VolGroup00/LogVol01
    # Path: /
    - lvol: vg=VolGroup00 lv=LogVol03 size=400g
    - command: xfs_growfs /dev/VolGroup00/LogVol03
    # Path: /data
    - file: state=directory path=/data
  become: yes
  gather_facts: no
