---

# NAME                    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
# sda                       8:0    0 279.5G  0 disk 
# ├─sda1                    8:1    0     1G  0 part /boot
# └─sda2                    8:2    0 278.5G  0 part 
#   ├─VolGroup00-LogVol03 253:0    0    20G  0 lvm  /
#   ├─VolGroup00-LogVol00 253:1    0    28G  0 lvm  [SWAP]
#   ├─VolGroup00-LogVol02 253:3    0     4G  0 lvm  /var
#   └─VolGroup00-LogVol01 253:4    0     1G  0 lvm  /tmp
# sdb                       8:16   0 279.5G  0 disk 
# sdc                       8:32   0 279.4G  0 disk

- hosts: "{{ group }}"
  tasks:
  # - command: mdadm --stop /dev/md127
    - command: mdadm --zero-superblock /dev/sdb /dev/sdc
    - command: mdadm --create --run /dev/md127 -l 0 -n 2 /dev/sdb /dev/sdc
      # mdadm --detail /dev/md127

    - lvg:  vg=VolGroup01 pvs=/dev/md127
    # Docker library (/var/lib/docker/containers)
    - lvol: vg=VolGroup01 lv=LogVol00 size=200g
    - filesystem: fstype=xfs dev=/dev/VolGroup01/LogVol00
    - file: state=directory path=/var/lib/docker
    - mount: name=/var/lib/docker src=/dev/VolGroup01/LogVol00 fstype=xfs opts="defaults" state=mounted
    # Docker thin pool (/var/lib/docker/devicemapper)
    - command: lvcreate -L 300g --thin VolGroup01/ThinPool00 --poolmetadatasize 256m

    # Remove SWAP
    - command: swapoff -a
    - mount: name=swap src=/dev/VolGroup00/LogVol00 state=absent
    - command: lvremove --force VolGroup00/LogVol00
    # Important
    - command: sed -i 's/rd.lvm.lv=VolGroup00\/LogVol00//g' /etc/default/grub
    - command: grub2-mkconfig -o /boot/grub2/grub.cfg

    # Path: /tmp
    - lvol: vg=VolGroup00 lv=LogVol01 size=20g
    - command: xfs_growfs /dev/VolGroup00/LogVol01
    # Path: /var
    - lvol: vg=VolGroup00 lv=LogVol02 size=150g
    - command: xfs_growfs /dev/VolGroup00/LogVol02
    # Path: /
    - lvol: vg=VolGroup00 lv=LogVol03 size=100g
    - command: xfs_growfs /dev/VolGroup00/LogVol03
    # Path: /data
    - file: state=directory path=/data
  become: yes
  gather_facts: no
