---
### calico step 1
- hosts: "{{ group }}"
  serial: 5
  tasks:
    - shell: "/usr/sbin/ethtool eth0 | grep Speed | awk '{print $2}'"
      register: eth0_result
      ignore_errors: yes

    - shell: "/usr/sbin/ethtool eth2 | grep Speed | awk '{print $2}'"
      register: eth2_result
      ignore_errors: yes

    # TODO: Call NOSA API in CMDB
    # Update TOR: https://network.wz.net/network/readme/
    - name: eth0 as iface
      local_action: "command /bin/sh ../files/del_bgp.sh {{ calico_idc }} {{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }} {{ hostvars[inventory_hostname]['ansible_eth0']['macaddress'] }}"
      when: eth0_result.failed == False and eth0_result.stdout == "1000Mb/s"
      become: false
    - name: eth0 as iface
      local_action: "command /bin/sh ../files/del_bgp.sh {{ calico_idc }} {{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }} {{ hostvars[inventory_hostname]['ansible_eth0']['macaddress'] }}"
      when: eth0_result.failed == False and eth0_result.stdout == "10000Mb/s"
      become: false
    - name: eth2 as iface
      local_action: "command /bin/sh ../files/del_bgp.sh {{ calico_idc }} {{ hostvars[inventory_hostname]['ansible_eth2']['ipv4']['address'] }} {{ hostvars[inventory_hostname]['ansible_eth2']['macaddress'] }}"
      when: eth2_result.failed == False and eth2_result.stdout == "10000Mb/s"
      become: false
  become: yes
  gather_facts: yes
