- lineinfile: dest=/etc/sysctl.d/99-sysctl.conf state=absent
    regexp="^net\.ipv6"
- sysctl:
    name: net.core.somaxconn
    value: 1000
    state: present
- sysctl:
    name: net.core.netdev_max_backlog
    value: 5000
    state: present
- sysctl:
    name: net.core.rmem_default
    value: 16777216
    state: present
- sysctl:
    name: net.core.rmem_max
    value: 16777216
    state: present
- sysctl:
    name: net.core.wmem_default
    value: 16777216
    state: present
- sysctl:
    name: net.core.wmem_max
    value: 16777216
    state: present
- sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 2
    state: present
- sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 2
    state: present
- sysctl:
    name: net.ipv4.tcp_wmem
    value: 4096 12582912 16777216
    state: present
- sysctl:
    name: net.ipv4.tcp_rmem
    value: 4096 12582912 16777216
    state: present
- sysctl:
    name: net.ipv4.udp_wmem_min
    value: 16384
    state: present
- sysctl:
    name: net.ipv4.udp_rmem_min
    value: 16384
    state: present
- sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 8096
    state: present
- sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: 0
    state: present
- sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    state: present
- sysctl:
    name: net.ipv4.ip_local_port_range
    value: 10240 65535
    state: present
- sysctl:
    name: net.unix.max_dgram_qlen
    value: 512
    state: present
- sysctl:
    name: net.core.rps_sock_flow_entries
    value: 65536
    state: present
- template: src=../templates/ifup-local.j2 dest=/sbin/ifup-local mode=0755
  ignore_errors: true

# arp related
- sysctl:
    name: net.ipv4.neigh.default.gc_thresh1
    value: 1024
    state: present
- sysctl:
    name: net.ipv4.neigh.default.gc_thresh2
    value: 2048
    state: present
- sysctl:
    name: net.ipv4.neigh.default.gc_thresh3
    value: 4096
    state: present
- sysctl:
    name: net.ipv4.neigh.default.gc_interval
    value: 60
    state: present
- sysctl:
    name: net.ipv4.neigh.default.gc_stale_time
    value: 180
    state: present
- sysctl:
    name: net.ipv4.neigh.default.base_reachable_time_ms
    value: 60000
    state: present
- sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

# conntrack related
- command: modprobe nf_conntrack_ipv4
  ignore_errors: yes
- command: modprobe nf_conntrack
  ignore_errors: yes
- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_established
    value: 900
    state: present
- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_time_wait
    value: 120
    state: present
- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_close_wait
    value: 60
    state: present
- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_fin_wait
    value: 120
    state: present
# HASHSIZE = CONNTRACK_MAX / 8 = RAMSIZE (in bytes) / 131072 / (x / 32)
- sysctl:
    name: net.netfilter.nf_conntrack_max
    value: "{{ (ansible_memtotal_mb * 1024 * 1024 / 131072 / (64 / 32) * 8)|int }}"
    state: present
- template: src=../templates/nf_conntrack.modules.j2 dest=/etc/sysconfig/modules/nf_conntrack.modules mode=0755
  ignore_errors: true
- command: sysctl --load

