- hosts: "{{ group }}"
  become: yes
  gather_facts: true

  serial: 1

  tasks:
    - service: name=firewalld state=stopped enabled=no
    - service: name=telegraf state=stopped enabled=no
    - service: name=kube-proxy state=stopped enabled=yes

    - file:
        state=directory
        path="{{ telegraf_home }}/scripts"
        owner={{ telegraf_user }} group={{ telegraf_group }}
    - copy: src=../files/telegraf/lsmod.sh dest="{{ telegraf_home }}/scripts/" mode="ugo+x"
    - copy: src=../files/telegraf-1.10.1-1.x86_64.rpm dest="/tmp/"

    - yum: name=/tmp/telegraf-1.10.1-1.x86_64.rpm state=present disablerepo=cloudcentos7-base-x86_64,cloudcentos7-base-noarch,cloudcentos7-liberty_base-noarch,cloudcentos7-liberty_base-x86_64,cloudcentos7-production-x86_64,cloudcentos7-production-noarch
      ignore_errors: true
    - yum: name=/tmp/telegraf-1.10.1-1.x86_64.rpm state=present

    - template:
        src="../templates/telegraf.service.j2"
        dest="/etc/systemd/system/telegraf.service"
    - template:
        src="../templates/telegraf-edgenode.conf.j2" dest="{{ telegraf_config }}" owner={{ telegraf_user }} group={{ telegraf_group }}
    - command: systemctl daemon-reload
    - command: mkdir -p /data/log

    - service: name=telegraf state=restarted enabled=yes
    - service: name=kube-proxy state=started enabled=yes
