---

# Copy the instance specific default file
- name: Copy Default File for Instance
  template:
    src=sysconfig/elasticsearch.j2
    dest=/etc/sysconfig/elasticsearch-{{ es_instance_name }}
    mode=0644 force=yes

# Copy the systemd specific file if systemd is installed
- name: Copy Systemd File for Instance
  template:
    src=systemd/elasticsearch.service.j2
    dest=/etc/systemd/system/elasticsearch-{{ es_instance_name }}.service
    mode=0644 force=yes

- command: systemctl daemon-reload

