---

- name: Create data dir
  file: state=directory path={{ es_data_dir }} owner={{ es_user }} group={{ es_group }}

- name: Create log dir
  file: state=directory path={{ es_log_dir }} owner={{ es_user }} group={{ es_group }}

- name: Create config Directory
  file: state=directory path={{ es_conf_dir }} owner={{ es_user }} group={{ es_group }}

# Copy the config template
- name: Copy Configuration File
  template:
    src=elasticsearch.yml.j2
    dest={{ es_conf_dir }}/elasticsearch.yml
    owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  tags:
    - configuration

# Copy the logging.yml
- name: Copy Logging.yml File for Instance
  template:
    src=logging.yml.j2
    dest={{ es_conf_dir }}/logging.yml
    owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  tags:
    - configuration
