---
- hosts: "{{ group }}"
  vars_files:
    - "inventory/vars/{{ group }}"
    - "inventory/vars/{{ vault }}.vault"
  remote_user: group
  roles:
    - telegraf
  tasks:
    - template:
        src="templates/{{ telegraf_template }}"
        dest="{{ telegraf_config }}"
        owner={{ telegraf_user }} group={{ telegraf_group }}
      tags: configuration
  become: no
  gather_facts: yes
