apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    app: busybox1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - docker12034idc
  containers:
  - image: busybox
    command:
      - sleep
      - "wz0"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
