---
- hosts: "{{ group }}"
  serial: 5
  vars:
    kernel_version: 3.10.0-514.10.2.el7.ttm.x86_64
  tasks:
    - name: Create file blacklist-nouveau.conf with content
      copy:
        dest: "/etc/modprobe.d/blacklist-nouveau.conf"
        content: |
          blacklist nouveau
          options nouveau modeset=0
    - name: Backup boot image
      command: mv /boot/initramfs-{{ kernel_version }}.img /boot/initramfs-{{ kernel_version }}.img.bak
      ignore_errors: true
    - name: Create new boot image
      command: dracut /boot/initramfs-{{ kernel_version }}.img {{ kernel_version }}
    - name: Reboot
      command: reboot
  become: yes
  gather_facts: true
